### ISSUE TITLE
Wrong client DTO format

### ISSUE THREAD

**Issue by Krasnyanskiy** [Jaspersoft/jrs-rest-java-client#142]
If I need to create a calendar via RESTv2 services I can use our `JobsService`. See example below:

```java
WeeklyCalendar calendar = new WeeklyCalendar();

calendar.setDescription("ACalendarForTheTestPurposes");
calendar.setTimeZone(TimeZone.getTimeZone("GMT+03:00"));
calendar.setExcludeDaysFlags(new boolean[]{
        true,   // Sunday
        false,  // Monday
        false,  // Tuesday
        false,  // Wednesday
        false,  // Thursday
        true,   // Friday
        true    // Saturday
});

ReportJobCalendar jobCalendar = session
        .jobsService()
        .calendar("TestCalendar")
        .createNew(calendar)
        .getEntity();

String description = jobCalendar.getDescription();
assert("ACalendarForTheTestPurposes".equals(description));
```
The problem comes when server is trying to deserialize an entity. It sends me back an error:

```javascript
{
  "message": "mandatory parameter 'reportJobCalendar.excludeDaysFlags' not found",
  "errorCode": "mandatory.parameter.error",
  "parameters": ["reportJobCalendar.excludeDaysFlags"]
}
```
Here is a stacktrace:

```
Exception in thread "main" com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.MandatoryParameterNotFoundException: mandatory parameter 'reportJobCalendar.excludeDaysFlags' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.handling.DefaultErrorHandler.handleBodyError(DefaultErrorHandler.java:95)
	at com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.handling.DefaultErrorHandler.handleError(DefaultErrorHandler.java:67)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.executeRequest(JerseyRequest.java:178)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.put(JerseyRequest.java:128)
	at com.jaspersoft.jasperserver.jaxrs.client.apiadapters.jobs.calendar.SingleCalendarOperationsAdapter.createNew(SingleCalendarOperationsAdapter.java:157)
	at com.test.CalendarTest.main(CalendarTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by yaroslav-kovalchyk** [comment]
Couldn't reproduce with the latest version of client. Please double check steps. If something is missing, then please add more information and reopen the issue. Would be great to see your failing test in https://github.com/Jaspersoft/jrs-rest-java-client-tests
