### ISSUE TITLE
Question: Jasper caching

### ISSUE THREAD

**Issue by jasminkaldzija** [Jaspersoft/jrs-rest-java-client#148]
Hi everyone,

How can I delete report execution from execution list? I want to remove that from session after exporting it (it uses a lot of memory)?

Sincerely,
Jasmin

**Comment by yaroslav-kovalchyk** [comment]
Hi Jasmin,
very good question. Currently JasperReportsServer doesn't provide this functionality, but it's definitely needed. I'll create enhancement request for that.

**Comment by jasminkaldzija** [comment]
Nice. Will session executions be deleted from JasperReport Server after calling "session.logout()"?

**Comment by yaroslav-kovalchyk** [comment]
yes. Currently logout is the only way to clear reportExecutions from memory.

**Comment by jasminkaldzija** [comment]
Thank you. "session.logout()" will be good enough for now, but I'm still waiting for new functionality :yum:

**Comment by yaroslav-kovalchyk** [comment]
If you need some more functionality, than just removing of reportExecutions from memory, then fill free to file more issues here.
Thank you for this valuable feedback.

**Comment by jasminkaldzija** [comment]
Thank you. 

Actually there is one more thing. Is there any way to find out "totalPages" before reportExecution turn to "ready" status. When status turns to "execution" it starts filling "report" and it increases "currentPage" but "totalPages" is null. Or, is there any way to make estimation time for reportExecution (not necessary in time format, it can be in percentages) ?

Sincerely,
Jasmin

**Comment by yaroslav-kovalchyk** [comment]
Hi Jasmin,
I see your issue, but unfortunately there is no way to know totalPages before execution is ready.

**Comment by jasminkaldzija** [comment]
Hi Yaroslav,

I want to report something. I'm not sure what exactly is problem. When I generate report which returns pdf file with 20 000 pages it works fine.  But problem is with report with 70 000 pages. Whey execution turns from "execution" to ready, export status should be changed from "queue" to "execution". In by case it turns to "cancelled".("Report generation cancelled" in server log).

Version of server is 5.6.0

Sincerely,
Jasmin

**Comment by yaroslav-kovalchyk** [comment]
It's technical cancel, that happens on report execution complete. It shouldn't be visible outside, but unfortunately it is visible and confusing users. We will fix it. For now just ignore this status and load your output resource, cancelled export will be restarted automatically.

**Comment by jasminkaldzija** [comment]
Hi Yaroslav,

In my case sometimes export get status "cancelled" before execution is finished. Than I run it again(create new export request) and it works fine. But if I run 2+ executions, export status become "failed" with exception:

(Unexpected error)
java.lang.NullPointerException at com.jaspersoft.jasperserver.remote.services.impl.RunReportServiceImpl.executeExport(RunReportServiceImpl.java:380) at com.jaspersoft.jasperserver.remote.services.impl.RunReportServiceImpl$2.run(RunReportServiceImpl.java:343) at com.jaspersoft.jasperserver.api.logging.util.LoggableExecutorService$1.run(LoggableExecutorService.java:59) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)

Sincerely,
Jasmin

**Comment by yaroslav-kovalchyk** [comment]
Hi Jasmin,
what server version are you using?

**Comment by yaroslav-kovalchyk** [comment]
Closed by mistake

**Comment by jasminkaldzija** [comment]
I use 5.6.0 version.

This is how I launch report:
...
...
  executionRequest
                .setAsync(true)
                .setOutputFormat("PDF");
      
 executionRequest.setReportUnitUri(path + "/"+reportId);
...
...
...
OperationResult<ReportExecutionDescriptor> result = session.reportingService().
                newReportExecutionRequest(executionRequest)

**Comment by yaroslav-kovalchyk** [comment]
Rather old version... 
It's definitely server side issue and I suppose this issue is already fixed in latest version. Please upgrade if possible. Otherwise you can contact our technical support.

**Comment by jasminkaldzija** [comment]
Thank you Yaroslav, 
I will try one of the newer version.

**Comment by rajeev315** [comment]
Hi everyone,
Here is the issue I am facing:
One user has access to report 1 in which  ABCD data is available  and E is missing and once she clicks on home log out log back in and refresh and open the report again then she can see ABCDE in the  report. at the same time I have opened the same report and I was able to see ABCDE. What could be the reason she was not able to see ABCDE in the first place is it some thing to do with Browser Cache. Please advise.

Thanks,
Rajeev
