### ISSUE TITLE
Dependency on JAX-RS 1.x

### ISSUE THREAD

**Issue by pdolezal** [Jaspersoft/jrs-rest-java-client#221]
The REST client depends on both JAX-RS 1.x and JAX-RS 2.0, e.g., `jsr311-api-1.1.1.jar` is pulled by the POM. It seems to cause problems… sometimes: depending on the classpath ordering, an application using the REST client may run, or crash with exceptions like this one:

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
  at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:122)
  at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
  at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
  at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:80)
  at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:99)
  at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:71)
  at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:290)
  at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:76)
  at com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.init(SessionStorage.java:122)
  at com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.<init>(SessionStorage.java:77)
  at com.jaspersoft.jasperserver.jaxrs.client.core.JasperserverRestClient.authenticate(JasperserverRestClient.java:75)
  at com.jaspersoft.jasperserver.jaxrs.client.core.JasperserverRestClient.authenticate(JasperserverRestClient.java:50)
```

Unfortunately, naïve removal of JAX-RS 1.x dependencies causes other kinds of similar issues, so I guess it needs a more precise fix.

**Comment by slecuyer** [comment]
It's a bug. 

Replace         
<dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-json</artifactId>
            <version>1.19</version>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey.contribs</groupId>
            <artifactId>jersey-multipart</artifactId>
            <version>1.19</version>
        </dependency>

by 

 
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.22.1</version>
</dependency>
<dependency>
    <groupId>org.codehaus.jackson</groupId>
    <artifactId>jackson-jaxrs</artifactId>
    <version>1.9.12</version>
</dependency>
<dependency>
    <groupId>org.codehaus.jettison</groupId>
    <artifactId>jettison</artifactId>
    <version>1.3.6</version>
</dependency>
<dependency>
    <groupId>org.codehaus.jackson</groupId>
    <artifactId>jackson-xc</artifactId>
    <version>1.9.12</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.22.1</version>
</dependency>
<dependency>
     <groupId>org.glassfish.jersey.media</groupId>
     <artifactId>jersey-media-json-jackson</artifactId>
     <version>2.22.1</version>
</dependency>

and delete/change old import in java class

**Comment by tggm** [comment]
Can we expect an updated version of the library with this fix. It's hell to use on Jboss/Wildfly.
