### ISSUE TITLE
When getting data, in what situation will Bad Request occur ?

### ISSUE THREAD

**Issue by peteryuanpan** [Jaspersoft/jrs-rest-java-client#347]
HI

I've meet a difficult problem that can not solve. I would like to ask for help. Would you please have a look in few minutes? Thanks.

I got data from japser server by following code:

public static InputStream organizationReport() {
&emsp;&emsp;OperationResult<InputStream> result = client
&emsp;&emsp;&emsp;&emsp;.authenticate(Constant.ServerInfo.userName, Constant.ServerInfo.password)
&emsp;&emsp;&emsp;&emsp;.reportingService()
&emsp;&emsp;&emsp;&emsp;.report(Constants.P84_ORGANIZATION_REPORT_URI)
&emsp;&emsp;&emsp;&emsp;.prepareForRun(ReportOutputFormat.CSV)
&emsp;&emsp;&emsp;&emsp;.parameter("Cascading_name_single_select", "A & U Stalker Telecommunications, Inc")
&emsp;&emsp;&emsp;&emsp;.run();
&emsp;&emsp;InputStream report = result.getEntity();
&emsp;&emsp;return report;
}

However, there are plenty of permission information on my server. And sometimes I got following error:

2018-01-05 11:18:26.969 ERROR P84PermissionAnchorPaneReport:? - Bad Request
com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.BadRequestException: Bad Request
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.handling.DefaultErrorHandler.handleStatusCodeError(DefaultErrorHandler.java:111)
at com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.handling.DefaultErrorHandler.handleError(DefaultErrorHandler.java:68)
at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.executeRequest(JerseyRequest.java:189)
at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.executeRequest(JerseyRequest.java:153)
at com.jaspersoft.jasperserver.jaxrs.client.apiadapters.reporting.RunReportAdapter.run(RunReportAdapter.java:98)
at com.legendapl.lightning.tools.service.ExecuteAPIService.organizationReport(Unknown Source)
.................

My main question is:
I know when creating data to server, sometimes Bad Request will occur. However this time I got Bad Request when getting data.
I would like to ask, in what situation, if you know, Bad Request will occur when getting data from server ?

Thank you very much.

**Comment by tmatveyeva** [comment]
Hello,

Bad request occurs not when you getting data, but when you request it from server. For your information, there are two strategies to handle exceptions by rest client. Please look for exception handling in the documentation.

Regards,
Tetyana
