### ISSUE TITLE
String index out of range: -14

### ISSUE THREAD

**Issue by Angelic23** [Jaspersoft/jrs-rest-java-client#348]
Hi.

I'm new using this API, I just want to call a report using this:

```
OperationResult<InputStream> result = client
                .authenticate("jasper", "jasper")
                .reportingService()
                .report("/reports/Campaña/Campaña_DobleMEGAS")
                .prepareForRun(ReportOutputFormat.PDF, 1)
                .run();
InputStream report = result.getEntity();
```

But I'm getting this error:

``
Exception in thread "main" com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.UnexpectedErrorException: String index out of range: -14
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.handling.DefaultErrorHandler.handleBodyError(DefaultErrorHandler.java:95)
	at com.jaspersoft.jasperserver.jaxrs.client.apiadapters.reporting.RunReportErrorHandler.handleBodyError(RunReportErrorHandler.java:38)
	at com.jaspersoft.jasperserver.jaxrs.client.core.exceptions.handling.DefaultErrorHandler.handleError(DefaultErrorHandler.java:67)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.executeRequest(JerseyRequest.java:204)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.executeRequest(JerseyRequest.java:168)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.get(JerseyRequest.java:137)
	at com.jaspersoft.jasperserver.jaxrs.client.apiadapters.reporting.RunReportAdapter.run(RunReportAdapter.java:114)
``
Do you know if I'm doing something wrong in the call??

Thanks for help.

**Comment by tmatveyeva** [comment]
Hello,

Not sure what happened here, is it request work without this java REST client? just in any other REST client? I suppose there is something wrong with report

Regards,
Tetyana
