### ISSUE TITLE
Read time out issue with JRS 7.1 server

### ISSUE THREAD

**Issue by Rahamathulla** [Jaspersoft/jrs-rest-java-client#359]
I am in the process of evaluating Jaspersoft REport server 7.1

I am getting the below exception while trying to execute a sample program.

Exception in thread "main" javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.executeRequest(JerseyRequest.java:185)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JerseyRequest.post(JerseyRequest.java:155)
	at com.jaspersoft.jasperserver.jaxrs.client.apiadapters.reporting.ReportingService.newReportExecutionRequest(ReportingService.java:48)
	at com.nelson.ecd.reporting.rest.JasperReportClient.main(JasperReportClient.java:33)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 14 more

1) I am setting jasperserverVersion=v6_1_0 in the configuration properties file, though i use latest JRS 7.1.0. Because there is no enum with 7.1.0 value in the library.

2) can the current version jrs client 6.3 be used with 7.1 version?

3) if its not usable what s the work around or solution?

please provide sample code to hit the JRS 7.1 server and execute reports in async mode.

**Comment by mjw4tson** [comment]
We've come across a similar issue while attempted to update to 7.x/8.x versions of JRS. It looks like the authentication API has changed which breaks the latest version of this library.

It seems like this isn't being actively maintained.

**Comment by kothanav** [comment]
Any update on this ? I have a requirement to do the same now. Is this project dead ?

**Comment by Oboros** [comment]
@tmatveyeva could you speak on whether a stable release for v.7.1.x will be released?

**Comment by afurlane** [comment]
I run into this issue searching for the connection timeout, I found that setting the timeout before getting the session fixes the problem. I'm a bit tired today to comment this further. Maybe tomorrow I'll end up posting code and possible reason for this behaviour.
